name: pipeline

on:
     push:
         branches: [ "main" ]

jobs:
     job1:
           name: 'Instalation and run Linting'
           runs-on: ubuntu-latest
           steps:
              #Step para correr el test de flake8
              - name: 'Instalo flake8'
                run: pip install flake8
              #Step para correr el test de pylint
              - name: 'Instalo pylint'
                run: pip install pylint
              #Step para correr el test de flake8
              - name: 'Correr flake8'
                run: flake8 main.py
              #Step para correr el test de pylint
              - name: 'Correr pylint'
                run: pylint main.py

     job2:
           needs: [ job1 ]
           name: 'Uni Test'
           runs-on: ubuntu-latest
           steps:
              - uses: actions/checkout@v3
              #Step para correr el test de flake8
              - name: 'Correr el uni test'
                run: python -m unittest --verbose --failfast

     job3: 
           needs: [ job2 ]
           name: 'Ejecucion del script main y guardar el resultado en un artefacto'
           runs-on: ubuntu-latest
           steps:
             - uses: actions/checkout@v3
             #Step que corre el script main
             - name: 'Correr script'
               run: python main.py
            #Step que sube el archivo
             - uses: actions/upload-artifact@v3
               with:
                  name: build
                  path: build
                
                
           
